[2024-11-26T14:52:32.581+0000] {processor.py:186} INFO - Started process (PID=1971) to work on /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:52:32.582+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firestore_s3_rds.py for tasks to queue
[2024-11-26T14:52:32.583+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:52:32.582+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:52:32.603+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:52:32.599+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firestore_s3_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firestore_s3_rds.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T14:52:32.605+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:52:32.625+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firestore_s3_rds.py took 0.049 seconds
[2024-11-26T14:53:03.449+0000] {processor.py:186} INFO - Started process (PID=2034) to work on /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:53:03.450+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firestore_s3_rds.py for tasks to queue
[2024-11-26T14:53:03.452+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:53:03.451+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:53:03.463+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:53:03.460+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firestore_s3_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firestore_s3_rds.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T14:53:03.464+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:53:03.480+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firestore_s3_rds.py took 0.036 seconds
[2024-11-26T14:53:34.322+0000] {processor.py:186} INFO - Started process (PID=2094) to work on /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:53:34.323+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firestore_s3_rds.py for tasks to queue
[2024-11-26T14:53:34.324+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:53:34.324+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:53:34.337+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:53:34.334+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firestore_s3_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firestore_s3_rds.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T14:53:34.338+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:53:34.354+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firestore_s3_rds.py took 0.039 seconds
[2024-11-26T14:54:04.547+0000] {processor.py:186} INFO - Started process (PID=2157) to work on /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:54:04.549+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firestore_s3_rds.py for tasks to queue
[2024-11-26T14:54:04.551+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:54:04.551+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:54:04.567+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:54:04.564+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firestore_s3_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firestore_s3_rds.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T14:54:04.569+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:54:04.589+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firestore_s3_rds.py took 0.050 seconds
[2024-11-26T14:54:34.955+0000] {processor.py:186} INFO - Started process (PID=2210) to work on /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:54:34.956+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firestore_s3_rds.py for tasks to queue
[2024-11-26T14:54:34.957+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:54:34.957+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:54:34.970+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:54:34.967+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firestore_s3_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firestore_s3_rds.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T14:54:34.971+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:54:34.990+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firestore_s3_rds.py took 0.040 seconds
[2024-11-26T14:55:05.235+0000] {processor.py:186} INFO - Started process (PID=2274) to work on /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:55:05.236+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firestore_s3_rds.py for tasks to queue
[2024-11-26T14:55:05.237+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:55:05.237+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:55:05.274+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:55:05.270+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firestore_s3_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firestore_s3_rds.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T14:55:05.275+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:55:05.293+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firestore_s3_rds.py took 0.064 seconds
[2024-11-26T14:55:35.593+0000] {processor.py:186} INFO - Started process (PID=2339) to work on /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:55:35.595+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firestore_s3_rds.py for tasks to queue
[2024-11-26T14:55:35.596+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:55:35.596+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:55:35.620+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:55:35.615+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firestore_s3_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firestore_s3_rds.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T14:55:35.621+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:55:35.650+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firestore_s3_rds.py took 0.064 seconds
[2024-11-26T14:56:05.775+0000] {processor.py:186} INFO - Started process (PID=2393) to work on /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:56:05.776+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firestore_s3_rds.py for tasks to queue
[2024-11-26T14:56:05.777+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:56:05.777+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:56:05.790+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:56:05.787+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firestore_s3_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firestore_s3_rds.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T14:56:05.792+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:56:05.812+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firestore_s3_rds.py took 0.044 seconds
[2024-11-26T14:56:36.187+0000] {processor.py:186} INFO - Started process (PID=2458) to work on /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:56:36.188+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firestore_s3_rds.py for tasks to queue
[2024-11-26T14:56:36.190+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:56:36.189+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:56:36.205+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:56:36.203+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firestore_s3_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firestore_s3_rds.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T14:56:36.206+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:56:36.224+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firestore_s3_rds.py took 0.044 seconds
[2024-11-26T14:57:32.966+0000] {processor.py:186} INFO - Started process (PID=2575) to work on /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:57:32.967+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firestore_s3_rds.py for tasks to queue
[2024-11-26T14:57:32.968+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:57:32.968+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:57:32.993+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:57:32.990+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firestore_s3_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firestore_s3_rds.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T14:57:32.995+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:57:33.013+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firestore_s3_rds.py took 0.053 seconds
[2024-11-26T14:58:03.154+0000] {processor.py:186} INFO - Started process (PID=2641) to work on /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:58:03.155+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firestore_s3_rds.py for tasks to queue
[2024-11-26T14:58:03.157+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:58:03.156+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:58:03.171+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:58:03.167+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firestore_s3_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firestore_s3_rds.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T14:58:03.172+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:58:03.190+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firestore_s3_rds.py took 0.041 seconds
[2024-11-26T14:58:33.475+0000] {processor.py:186} INFO - Started process (PID=2707) to work on /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:58:33.476+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firestore_s3_rds.py for tasks to queue
[2024-11-26T14:58:33.478+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:58:33.477+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:58:33.488+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:58:33.486+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firestore_s3_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firestore_s3_rds.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T14:58:33.490+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:58:33.509+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firestore_s3_rds.py took 0.040 seconds
[2024-11-26T14:59:03.763+0000] {processor.py:186} INFO - Started process (PID=2773) to work on /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:59:03.765+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firestore_s3_rds.py for tasks to queue
[2024-11-26T14:59:03.767+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:59:03.766+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:59:03.781+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:59:03.778+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firestore_s3_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firestore_s3_rds.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T14:59:03.782+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:59:03.808+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firestore_s3_rds.py took 0.053 seconds
[2024-11-26T14:59:34.424+0000] {processor.py:186} INFO - Started process (PID=2839) to work on /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:59:34.425+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firestore_s3_rds.py for tasks to queue
[2024-11-26T14:59:34.427+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:59:34.426+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:59:34.442+0000] {logging_mixin.py:190} INFO - [2024-11-26T14:59:34.439+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firestore_s3_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firestore_s3_rds.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T14:59:34.443+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T14:59:34.889+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firestore_s3_rds.py took 0.472 seconds
[2024-11-26T15:00:05.238+0000] {processor.py:186} INFO - Started process (PID=2905) to work on /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:00:05.239+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firestore_s3_rds.py for tasks to queue
[2024-11-26T15:00:05.241+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:00:05.241+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:00:05.253+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:00:05.250+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firestore_s3_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firestore_s3_rds.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:00:05.254+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:00:05.270+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firestore_s3_rds.py took 0.040 seconds
[2024-11-26T15:00:36.245+0000] {processor.py:186} INFO - Started process (PID=2971) to work on /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:00:36.245+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firestore_s3_rds.py for tasks to queue
[2024-11-26T15:00:36.247+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:00:36.247+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:00:36.259+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:00:36.256+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firestore_s3_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firestore_s3_rds.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:00:36.260+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:00:36.280+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firestore_s3_rds.py took 0.041 seconds
[2024-11-26T15:01:06.610+0000] {processor.py:186} INFO - Started process (PID=3037) to work on /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:01:06.610+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firestore_s3_rds.py for tasks to queue
[2024-11-26T15:01:06.612+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:01:06.612+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:01:06.624+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:01:06.621+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firestore_s3_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firestore_s3_rds.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:01:06.626+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:01:06.646+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firestore_s3_rds.py took 0.043 seconds
[2024-11-26T15:01:37.037+0000] {processor.py:186} INFO - Started process (PID=3104) to work on /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:01:37.038+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firestore_s3_rds.py for tasks to queue
[2024-11-26T15:01:37.041+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:01:37.041+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:01:37.071+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:01:37.066+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firestore_s3_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firestore_s3_rds.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:01:37.073+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:01:37.090+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firestore_s3_rds.py took 0.063 seconds
[2024-11-26T15:02:07.446+0000] {processor.py:186} INFO - Started process (PID=3176) to work on /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:02:07.447+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firestore_s3_rds.py for tasks to queue
[2024-11-26T15:02:07.449+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:02:07.448+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:02:07.463+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:02:07.460+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firestore_s3_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firestore_s3_rds.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:02:07.465+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:02:07.484+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firestore_s3_rds.py took 0.043 seconds
[2024-11-26T15:02:37.715+0000] {processor.py:186} INFO - Started process (PID=3242) to work on /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:02:37.716+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firestore_s3_rds.py for tasks to queue
[2024-11-26T15:02:37.717+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:02:37.717+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:02:37.729+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:02:37.726+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firestore_s3_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firestore_s3_rds.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:02:37.730+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:02:37.752+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firestore_s3_rds.py took 0.044 seconds
[2024-11-26T15:03:08.562+0000] {processor.py:186} INFO - Started process (PID=3308) to work on /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:03:08.563+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firestore_s3_rds.py for tasks to queue
[2024-11-26T15:03:08.565+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:03:08.565+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:03:08.584+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:03:08.581+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firestore_s3_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firestore_s3_rds.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:03:08.586+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:03:08.605+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firestore_s3_rds.py took 0.051 seconds
[2024-11-26T15:03:39.241+0000] {processor.py:186} INFO - Started process (PID=3374) to work on /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:03:39.242+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firestore_s3_rds.py for tasks to queue
[2024-11-26T15:03:39.244+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:03:39.243+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:03:39.257+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:03:39.254+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firestore_s3_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firestore_s3_rds.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:03:39.258+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:03:39.274+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firestore_s3_rds.py took 0.039 seconds
[2024-11-26T15:04:09.547+0000] {processor.py:186} INFO - Started process (PID=3440) to work on /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:04:09.548+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firestore_s3_rds.py for tasks to queue
[2024-11-26T15:04:09.550+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:04:09.550+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:04:09.564+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:04:09.561+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firestore_s3_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firestore_s3_rds.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:04:09.565+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:04:09.583+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firestore_s3_rds.py took 0.041 seconds
[2024-11-26T15:04:40.078+0000] {processor.py:186} INFO - Started process (PID=3506) to work on /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:04:40.079+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firestore_s3_rds.py for tasks to queue
[2024-11-26T15:04:40.081+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:04:40.080+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:04:40.095+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:04:40.091+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firestore_s3_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firestore_s3_rds.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:04:40.096+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:04:40.117+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firestore_s3_rds.py took 0.047 seconds
[2024-11-26T15:05:10.189+0000] {processor.py:186} INFO - Started process (PID=3572) to work on /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:05:10.190+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firestore_s3_rds.py for tasks to queue
[2024-11-26T15:05:10.192+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:05:10.191+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:05:10.206+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:05:10.203+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firestore_s3_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firestore_s3_rds.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:05:10.207+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:05:10.229+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firestore_s3_rds.py took 0.046 seconds
[2024-11-26T15:05:40.711+0000] {processor.py:186} INFO - Started process (PID=3638) to work on /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:05:40.712+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firestore_s3_rds.py for tasks to queue
[2024-11-26T15:05:40.714+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:05:40.714+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:05:40.726+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:05:40.723+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firestore_s3_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firestore_s3_rds.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:05:40.727+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:05:40.747+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firestore_s3_rds.py took 0.042 seconds
[2024-11-26T15:06:11.257+0000] {processor.py:186} INFO - Started process (PID=3704) to work on /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:06:11.258+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firestore_s3_rds.py for tasks to queue
[2024-11-26T15:06:11.260+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:06:11.260+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:06:11.274+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:06:11.271+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firestore_s3_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firestore_s3_rds.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:06:11.276+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:06:11.294+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firestore_s3_rds.py took 0.042 seconds
[2024-11-26T15:06:41.460+0000] {processor.py:186} INFO - Started process (PID=3770) to work on /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:06:41.461+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firestore_s3_rds.py for tasks to queue
[2024-11-26T15:06:41.463+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:06:41.462+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:06:41.476+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:06:41.473+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firestore_s3_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firestore_s3_rds.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:06:41.477+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:06:41.496+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firestore_s3_rds.py took 0.042 seconds
[2024-11-26T15:07:11.882+0000] {processor.py:186} INFO - Started process (PID=3836) to work on /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:07:11.883+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firestore_s3_rds.py for tasks to queue
[2024-11-26T15:07:11.885+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:07:11.884+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:07:11.898+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:07:11.895+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firestore_s3_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firestore_s3_rds.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:07:11.899+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:07:11.919+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firestore_s3_rds.py took 0.043 seconds
[2024-11-26T15:07:42.442+0000] {processor.py:186} INFO - Started process (PID=3902) to work on /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:07:42.443+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firestore_s3_rds.py for tasks to queue
[2024-11-26T15:07:42.444+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:07:42.444+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:07:42.460+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:07:42.458+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firestore_s3_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firestore_s3_rds.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:07:42.461+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:07:42.647+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firestore_s3_rds.py took 0.211 seconds
[2024-11-26T15:08:13.621+0000] {processor.py:186} INFO - Started process (PID=3968) to work on /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:08:13.621+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firestore_s3_rds.py for tasks to queue
[2024-11-26T15:08:13.623+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:08:13.623+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:08:13.636+0000] {logging_mixin.py:190} INFO - [2024-11-26T15:08:13.633+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firestore_s3_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firestore_s3_rds.py", line 2, in <module>
    from airflow.providers.google.cloud.hooks.firestore import FirestoreHook
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.hooks.firestore'
[2024-11-26T15:08:13.637+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firestore_s3_rds.py
[2024-11-26T15:08:13.655+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firestore_s3_rds.py took 0.040 seconds
