[2024-12-01T02:10:53.390+0000] {processor.py:186} INFO - Started process (PID=50515) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:10:53.392+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:10:53.407+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:10:53.407+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:10:53.466+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:10:53.462+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:10:53.467+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:10:53.509+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.133 seconds
[2024-12-01T02:11:24.423+0000] {processor.py:186} INFO - Started process (PID=50581) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:11:24.424+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:11:24.427+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:11:24.427+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:11:24.440+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:11:24.438+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:11:24.442+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:11:24.460+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.042 seconds
[2024-12-01T02:11:55.278+0000] {processor.py:186} INFO - Started process (PID=50648) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:11:55.279+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:11:55.281+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:11:55.281+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:11:55.296+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:11:55.293+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:11:55.297+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:11:55.315+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.042 seconds
[2024-12-01T02:12:25.825+0000] {processor.py:186} INFO - Started process (PID=50714) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:12:25.827+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:12:25.830+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:12:25.829+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:12:25.843+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:12:25.840+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:12:25.844+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:12:25.861+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.043 seconds
[2024-12-01T02:12:56.432+0000] {processor.py:186} INFO - Started process (PID=50780) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:12:56.434+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:12:56.437+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:12:56.437+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:12:56.455+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:12:56.451+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:12:56.456+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:12:56.489+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.065 seconds
[2024-12-01T02:13:27.313+0000] {processor.py:186} INFO - Started process (PID=50846) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:13:27.314+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:13:27.316+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:13:27.315+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:13:27.330+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:13:27.327+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:13:27.331+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:13:27.350+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.042 seconds
[2024-12-01T02:13:58.015+0000] {processor.py:186} INFO - Started process (PID=50912) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:13:58.016+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:13:58.020+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:13:58.019+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:13:58.036+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:13:58.033+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:13:58.037+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:13:58.055+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.048 seconds
[2024-12-01T02:14:28.320+0000] {processor.py:186} INFO - Started process (PID=50978) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:14:28.321+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:14:28.324+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:14:28.324+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:14:28.340+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:14:28.336+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:14:28.341+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:14:28.358+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.046 seconds
[2024-12-01T02:14:59.103+0000] {processor.py:186} INFO - Started process (PID=51050) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:14:59.104+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:14:59.106+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:14:59.106+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:14:59.118+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:14:59.115+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:14:59.119+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:14:59.139+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.041 seconds
[2024-12-01T02:15:30.076+0000] {processor.py:186} INFO - Started process (PID=51116) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:15:30.077+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:15:30.080+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:15:30.079+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:15:30.094+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:15:30.091+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:15:30.095+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:15:30.118+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.050 seconds
[2024-12-01T02:16:01.086+0000] {processor.py:186} INFO - Started process (PID=51182) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:16:01.087+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:16:01.089+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:16:01.089+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:16:01.102+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:16:01.100+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:16:01.103+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:16:01.121+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.040 seconds
[2024-12-01T02:16:31.713+0000] {processor.py:186} INFO - Started process (PID=51248) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:16:31.714+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:16:31.716+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:16:31.716+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:16:31.731+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:16:31.728+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:16:31.732+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:16:31.750+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.043 seconds
[2024-12-01T02:17:02.769+0000] {processor.py:186} INFO - Started process (PID=51314) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:17:02.770+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:17:02.772+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:17:02.772+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:17:02.788+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:17:02.784+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:17:02.789+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:17:02.808+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.046 seconds
[2024-12-01T02:17:33.744+0000] {processor.py:186} INFO - Started process (PID=51380) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:17:33.746+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:17:33.749+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:17:33.748+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:17:33.766+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:17:33.763+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:17:33.767+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:17:33.784+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.047 seconds
[2024-12-01T02:18:03.887+0000] {processor.py:186} INFO - Started process (PID=51446) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:18:03.888+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:18:03.891+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:18:03.890+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:18:03.914+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:18:03.911+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:18:03.915+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:18:03.931+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.049 seconds
[2024-12-01T02:18:34.786+0000] {processor.py:186} INFO - Started process (PID=51512) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:18:34.787+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:18:34.790+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:18:34.790+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:18:34.810+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:18:34.807+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:18:34.811+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:18:34.830+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.051 seconds
[2024-12-01T02:19:05.594+0000] {processor.py:186} INFO - Started process (PID=51579) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:19:05.595+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:19:05.597+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:19:05.597+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:19:05.614+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:19:05.611+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:19:05.616+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:19:05.634+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.051 seconds
[2024-12-01T02:19:35.877+0000] {processor.py:186} INFO - Started process (PID=51645) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:19:35.878+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:19:35.881+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:19:35.881+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:19:35.899+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:19:35.896+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:19:35.900+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:19:35.918+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.049 seconds
[2024-12-01T02:20:06.579+0000] {processor.py:186} INFO - Started process (PID=51711) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:20:06.580+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:20:06.583+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:20:06.583+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:20:06.598+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:20:06.595+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:20:06.599+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:20:06.616+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.048 seconds
[2024-12-01T02:20:36.842+0000] {processor.py:186} INFO - Started process (PID=51777) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:20:36.843+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:20:36.846+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:20:36.846+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:20:36.862+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:20:36.860+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:20:36.863+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:20:36.881+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.046 seconds
[2024-12-01T02:21:07.265+0000] {processor.py:186} INFO - Started process (PID=51843) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:21:07.266+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:21:07.268+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:21:07.268+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:21:07.281+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:21:07.278+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:21:07.282+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:21:07.299+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.040 seconds
[2024-12-01T02:21:37.411+0000] {processor.py:186} INFO - Started process (PID=51909) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:21:37.412+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:21:37.415+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:21:37.415+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:21:37.431+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:21:37.428+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:21:37.432+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:21:37.449+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.045 seconds
[2024-12-01T02:22:08.487+0000] {processor.py:186} INFO - Started process (PID=51975) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:22:08.489+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:22:08.492+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:22:08.492+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:22:08.507+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:22:08.504+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:22:08.508+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:22:08.526+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.046 seconds
[2024-12-01T02:22:38.909+0000] {processor.py:186} INFO - Started process (PID=52041) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:22:38.910+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:22:38.913+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:22:38.913+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:22:38.929+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:22:38.925+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:22:38.930+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:22:38.951+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.049 seconds
[2024-12-01T02:23:09.508+0000] {processor.py:186} INFO - Started process (PID=52107) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:23:09.509+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:23:09.511+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:23:09.511+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:23:09.529+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:23:09.525+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:23:09.530+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:23:09.548+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.047 seconds
[2024-12-01T02:23:39.767+0000] {processor.py:186} INFO - Started process (PID=52173) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:23:39.768+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:23:39.770+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:23:39.770+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:23:39.784+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:23:39.780+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:23:39.786+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:23:39.806+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.044 seconds
[2024-12-01T02:24:10.033+0000] {processor.py:186} INFO - Started process (PID=52239) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:24:10.034+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:24:10.037+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:24:10.036+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:24:10.050+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:24:10.047+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:24:10.051+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:24:10.069+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.041 seconds
[2024-12-01T02:24:40.579+0000] {processor.py:186} INFO - Started process (PID=52305) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:24:40.581+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:24:40.583+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:24:40.583+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:24:40.599+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:24:40.596+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:24:40.600+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:24:40.619+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.046 seconds
[2024-12-01T02:25:11.010+0000] {processor.py:186} INFO - Started process (PID=52371) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:25:11.012+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:25:11.016+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:25:11.015+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:25:11.031+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:25:11.028+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:25:11.032+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:25:11.050+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.048 seconds
[2024-12-01T02:25:41.549+0000] {processor.py:186} INFO - Started process (PID=52437) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:25:41.551+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:25:41.554+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:25:41.553+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:25:41.569+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:25:41.566+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:25:41.570+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:25:41.588+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.046 seconds
[2024-12-01T02:26:12.244+0000] {processor.py:186} INFO - Started process (PID=52503) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:26:12.245+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:26:12.247+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:26:12.246+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:26:12.260+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:26:12.257+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:26:12.261+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:26:12.280+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.042 seconds
[2024-12-01T02:26:42.859+0000] {processor.py:186} INFO - Started process (PID=52569) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:26:42.860+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:26:42.862+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:26:42.861+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:26:42.875+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:26:42.872+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:26:42.875+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:26:42.894+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.041 seconds
[2024-12-01T02:27:13.364+0000] {processor.py:186} INFO - Started process (PID=52635) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:27:13.369+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:27:13.374+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:27:13.373+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:27:13.398+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:27:13.392+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:27:13.400+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:27:13.422+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.071 seconds
[2024-12-01T02:27:43.838+0000] {processor.py:186} INFO - Started process (PID=52701) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:27:43.839+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:27:43.841+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:27:43.841+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:27:43.858+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:27:43.855+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:27:43.859+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:27:43.879+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.055 seconds
[2024-12-01T02:28:14.246+0000] {processor.py:186} INFO - Started process (PID=52767) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:28:14.247+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:28:14.251+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:28:14.250+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:28:14.267+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:28:14.264+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:28:14.268+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:28:14.286+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.048 seconds
[2024-12-01T02:28:44.821+0000] {processor.py:186} INFO - Started process (PID=52833) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:28:44.822+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:28:44.825+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:28:44.824+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:28:44.838+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:28:44.835+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:28:44.839+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:28:44.857+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.043 seconds
[2024-12-01T02:29:15.301+0000] {processor.py:186} INFO - Started process (PID=52899) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:29:15.303+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:29:15.306+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:29:15.306+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:29:15.340+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:29:15.327+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:29:15.343+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:29:15.378+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.092 seconds
[2024-12-01T02:29:45.904+0000] {processor.py:186} INFO - Started process (PID=52965) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:29:45.905+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:29:45.909+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:29:45.909+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:29:45.925+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:29:45.922+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:29:45.926+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:29:45.943+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.050 seconds
[2024-12-01T02:30:16.276+0000] {processor.py:186} INFO - Started process (PID=53031) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:30:16.277+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:30:16.279+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:30:16.278+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:30:16.292+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:30:16.289+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:30:16.294+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:30:16.310+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.040 seconds
[2024-12-01T02:30:47.073+0000] {processor.py:186} INFO - Started process (PID=53097) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:30:47.074+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:30:47.077+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:30:47.076+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:30:47.096+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:30:47.093+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:30:47.097+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:30:47.115+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.049 seconds
[2024-12-01T02:31:17.392+0000] {processor.py:186} INFO - Started process (PID=53163) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:31:17.393+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:31:17.395+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:31:17.395+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:31:17.411+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:31:17.408+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:31:17.412+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:31:17.432+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.046 seconds
[2024-12-01T02:31:47.812+0000] {processor.py:186} INFO - Started process (PID=53229) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:31:47.813+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:31:47.816+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:31:47.816+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:31:47.829+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:31:47.827+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:31:47.830+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:31:47.848+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.044 seconds
[2024-12-01T02:32:18.255+0000] {processor.py:186} INFO - Started process (PID=53295) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:32:18.256+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:32:18.260+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:32:18.259+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:32:18.279+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:32:18.275+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:32:18.280+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:32:18.305+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.057 seconds
[2024-12-01T02:32:48.392+0000] {processor.py:186} INFO - Started process (PID=53361) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:32:48.393+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:32:48.395+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:32:48.395+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:32:48.411+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:32:48.408+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:32:48.412+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:32:48.439+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.053 seconds
[2024-12-01T02:33:18.561+0000] {processor.py:186} INFO - Started process (PID=53427) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:33:18.566+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:33:18.574+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:33:18.574+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:33:18.609+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:33:18.604+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:33:18.611+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:33:18.638+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.085 seconds
[2024-12-01T02:33:49.384+0000] {processor.py:186} INFO - Started process (PID=53493) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:33:49.386+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:33:49.389+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:33:49.388+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:33:49.406+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:33:49.404+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:33:49.407+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:33:49.424+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.046 seconds
[2024-12-01T02:34:20.179+0000] {processor.py:186} INFO - Started process (PID=53559) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:34:20.181+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:34:20.183+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:34:20.183+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:34:20.201+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:34:20.198+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:34:20.202+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:34:20.219+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.045 seconds
[2024-12-01T02:34:50.905+0000] {processor.py:186} INFO - Started process (PID=53625) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:34:50.906+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:34:50.908+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:34:50.908+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:34:50.924+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:34:50.921+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:34:50.925+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:34:50.943+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.043 seconds
[2024-12-01T02:35:21.829+0000] {processor.py:186} INFO - Started process (PID=53691) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:35:21.830+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-12-01T02:35:21.832+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:35:21.832+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:35:21.847+0000] {logging_mixin.py:190} INFO - [2024-12-01T02:35:21.844+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-12-01T02:35:21.848+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-12-01T02:35:21.864+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.041 seconds
