[2024-11-30T14:14:12.507+0000] {processor.py:186} INFO - Started process (PID=33527) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:14:12.508+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:14:12.520+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:14:12.519+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:14:12.584+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:14:12.562+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:14:12.615+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:14:12.801+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.303 seconds
[2024-11-30T14:14:43.600+0000] {processor.py:186} INFO - Started process (PID=33593) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:14:43.601+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:14:43.604+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:14:43.604+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:14:43.619+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:14:43.616+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:14:43.620+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:14:43.639+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.044 seconds
[2024-11-30T14:15:14.439+0000] {processor.py:186} INFO - Started process (PID=33659) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:15:14.440+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:15:14.442+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:15:14.442+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:15:14.464+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:15:14.460+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:15:14.465+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:15:14.483+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.050 seconds
[2024-11-30T14:15:44.634+0000] {processor.py:186} INFO - Started process (PID=33725) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:15:44.635+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:15:44.639+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:15:44.638+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:15:44.654+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:15:44.650+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:15:44.655+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:15:44.674+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.049 seconds
[2024-11-30T14:16:15.314+0000] {processor.py:186} INFO - Started process (PID=33791) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:16:15.315+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:16:15.319+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:16:15.318+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:16:15.333+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:16:15.330+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:16:15.334+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:16:15.352+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.045 seconds
[2024-11-30T14:16:45.795+0000] {processor.py:186} INFO - Started process (PID=33857) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:16:45.796+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:16:45.799+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:16:45.798+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:16:45.813+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:16:45.810+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:16:45.814+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:16:45.832+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.042 seconds
[2024-11-30T14:17:16.411+0000] {processor.py:186} INFO - Started process (PID=33923) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:17:16.412+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:17:16.415+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:17:16.414+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:17:16.429+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:17:16.426+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:17:16.430+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:17:16.452+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.047 seconds
[2024-11-30T14:17:47.204+0000] {processor.py:186} INFO - Started process (PID=33989) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:17:47.205+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:17:47.207+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:17:47.207+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:17:47.220+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:17:47.217+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:17:47.222+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:17:47.240+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.042 seconds
[2024-11-30T14:18:17.504+0000] {processor.py:186} INFO - Started process (PID=34055) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:18:17.505+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:18:17.508+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:18:17.507+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:18:17.522+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:18:17.519+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:18:17.523+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:18:17.541+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.043 seconds
[2024-11-30T14:18:47.898+0000] {processor.py:186} INFO - Started process (PID=34121) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:18:47.899+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:18:47.902+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:18:47.901+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:18:47.916+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:18:47.913+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:18:47.917+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:18:47.942+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.053 seconds
[2024-11-30T14:19:18.833+0000] {processor.py:186} INFO - Started process (PID=34187) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:19:18.835+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:19:18.837+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:19:18.837+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:19:18.852+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:19:18.849+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:19:18.853+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:19:18.870+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.045 seconds
[2024-11-30T14:19:49.082+0000] {processor.py:186} INFO - Started process (PID=34253) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:19:49.083+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:19:49.086+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:19:49.085+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:19:49.104+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:19:49.100+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:19:49.107+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:19:49.131+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.056 seconds
[2024-11-30T14:20:19.337+0000] {processor.py:186} INFO - Started process (PID=34319) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:20:19.338+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:20:19.341+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:20:19.340+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:20:19.359+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:20:19.355+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:20:19.361+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:20:19.382+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.052 seconds
[2024-11-30T14:20:49.884+0000] {processor.py:186} INFO - Started process (PID=34385) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:20:49.885+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:20:49.887+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:20:49.887+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:20:49.901+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:20:49.897+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:20:49.902+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:20:49.920+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.041 seconds
[2024-11-30T14:21:20.499+0000] {processor.py:186} INFO - Started process (PID=34451) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:21:20.501+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:21:20.503+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:21:20.502+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:21:20.517+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:21:20.513+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:21:20.518+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:21:20.535+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.041 seconds
[2024-11-30T14:21:51.608+0000] {processor.py:186} INFO - Started process (PID=34517) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:21:51.610+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:21:51.613+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:21:51.613+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:21:51.633+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:21:51.630+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:21:51.634+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:21:51.652+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.052 seconds
[2024-11-30T14:22:22.038+0000] {processor.py:186} INFO - Started process (PID=34583) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:22:22.039+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:22:22.041+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:22:22.041+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:22:22.055+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:22:22.052+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:22:22.056+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:22:22.073+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.041 seconds
[2024-11-30T14:22:52.591+0000] {processor.py:186} INFO - Started process (PID=34649) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:22:52.592+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:22:52.595+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:22:52.595+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:22:52.618+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:22:52.614+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:22:52.619+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:22:52.636+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.056 seconds
[2024-11-30T14:23:22.985+0000] {processor.py:186} INFO - Started process (PID=34716) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:23:22.986+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:23:22.988+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:23:22.988+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:23:23.002+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:23:22.999+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:23:23.003+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:23:23.020+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.040 seconds
[2024-11-30T14:23:53.288+0000] {processor.py:186} INFO - Started process (PID=34782) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:23:53.289+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:23:53.292+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:23:53.291+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:23:53.306+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:23:53.303+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:23:53.307+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:23:53.324+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.041 seconds
[2024-11-30T14:24:23.432+0000] {processor.py:186} INFO - Started process (PID=34848) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:24:23.433+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:24:23.436+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:24:23.435+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:24:23.451+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:24:23.448+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:24:23.453+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:24:23.469+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.042 seconds
[2024-11-30T14:24:53.777+0000] {processor.py:186} INFO - Started process (PID=34914) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:24:53.778+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:24:53.780+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:24:53.780+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:24:53.793+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:24:53.790+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:24:53.794+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:24:53.813+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.042 seconds
[2024-11-30T14:25:24.238+0000] {processor.py:186} INFO - Started process (PID=34980) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:25:24.239+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:25:24.241+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:25:24.241+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:25:24.254+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:25:24.251+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:25:24.255+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:25:24.273+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.044 seconds
[2024-11-30T14:25:54.338+0000] {processor.py:186} INFO - Started process (PID=35046) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:25:54.339+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:25:54.342+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:25:54.341+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:25:54.358+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:25:54.355+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:25:54.359+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:25:54.411+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.078 seconds
[2024-11-30T14:26:24.877+0000] {processor.py:186} INFO - Started process (PID=35112) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:26:24.878+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:26:24.881+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:26:24.880+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:26:24.901+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:26:24.896+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:26:24.902+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:26:24.918+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.048 seconds
[2024-11-30T14:26:55.123+0000] {processor.py:186} INFO - Started process (PID=35178) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:26:55.124+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:26:55.126+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:26:55.126+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:26:55.140+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:26:55.137+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:26:55.141+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:26:55.159+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.041 seconds
[2024-11-30T14:27:25.485+0000] {processor.py:186} INFO - Started process (PID=35244) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:27:25.485+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:27:25.488+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:27:25.487+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:27:25.503+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:27:25.500+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:27:25.505+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:27:25.523+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.045 seconds
[2024-11-30T14:27:56.049+0000] {processor.py:186} INFO - Started process (PID=35310) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:27:56.050+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:27:56.052+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:27:56.052+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:27:56.064+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:27:56.062+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:27:56.065+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:27:56.091+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.047 seconds
[2024-11-30T14:28:26.813+0000] {processor.py:186} INFO - Started process (PID=35376) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:28:26.814+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:28:26.817+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:28:26.816+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:28:26.829+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:28:26.826+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:28:26.830+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:28:26.847+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.040 seconds
[2024-11-30T14:28:57.250+0000] {processor.py:186} INFO - Started process (PID=35442) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:28:57.251+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:28:57.253+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:28:57.253+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:28:57.267+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:28:57.264+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:28:57.268+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:28:57.285+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.041 seconds
[2024-11-30T14:29:27.629+0000] {processor.py:186} INFO - Started process (PID=35508) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:29:27.630+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:29:27.632+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:29:27.632+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:29:27.646+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:29:27.642+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:29:27.647+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:29:27.666+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.042 seconds
[2024-11-30T14:29:57.844+0000] {processor.py:186} INFO - Started process (PID=35574) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:29:57.845+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:29:57.847+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:29:57.846+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:29:57.863+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:29:57.859+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:29:57.865+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:29:57.884+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.045 seconds
[2024-11-30T14:30:28.482+0000] {processor.py:186} INFO - Started process (PID=35640) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:30:28.483+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:30:28.486+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:30:28.485+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:30:28.500+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:30:28.497+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:30:28.502+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:30:28.522+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.046 seconds
[2024-11-30T14:30:58.809+0000] {processor.py:186} INFO - Started process (PID=35706) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:30:58.810+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:30:58.813+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:30:58.812+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:30:58.825+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:30:58.822+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:30:58.827+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:30:58.844+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.040 seconds
[2024-11-30T14:31:29.808+0000] {processor.py:186} INFO - Started process (PID=35772) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:31:29.809+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:31:29.812+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:31:29.812+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:31:29.827+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:31:29.823+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:31:29.828+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:31:29.846+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.045 seconds
[2024-11-30T14:32:00.467+0000] {processor.py:186} INFO - Started process (PID=35838) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:32:00.468+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:32:00.470+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:32:00.470+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:32:00.482+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:32:00.479+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:32:00.483+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:32:00.504+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.043 seconds
[2024-11-30T14:32:31.389+0000] {processor.py:186} INFO - Started process (PID=35904) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:32:31.390+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:32:31.393+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:32:31.392+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:32:31.411+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:32:31.408+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:32:31.412+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:32:31.431+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.051 seconds
[2024-11-30T14:33:01.489+0000] {processor.py:186} INFO - Started process (PID=35970) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:33:01.490+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:33:01.493+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:33:01.493+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:33:01.509+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:33:01.506+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:33:01.510+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:33:01.525+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.041 seconds
[2024-11-30T14:33:32.282+0000] {processor.py:186} INFO - Started process (PID=36036) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:33:32.283+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:33:32.286+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:33:32.286+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:33:32.304+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:33:32.300+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:33:32.305+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:33:32.323+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.049 seconds
[2024-11-30T14:34:02.721+0000] {processor.py:186} INFO - Started process (PID=36102) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:34:02.722+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:34:02.725+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:34:02.725+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:34:02.740+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:34:02.737+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:34:02.742+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:34:02.764+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.048 seconds
[2024-11-30T14:34:33.735+0000] {processor.py:186} INFO - Started process (PID=36168) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:34:33.736+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:34:33.738+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:34:33.738+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:34:33.753+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:34:33.749+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:34:33.754+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:34:33.771+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.042 seconds
[2024-11-30T14:35:04.506+0000] {processor.py:186} INFO - Started process (PID=36234) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:35:04.507+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:35:04.509+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:35:04.509+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:35:04.523+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:35:04.520+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:35:04.524+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:35:04.545+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.044 seconds
[2024-11-30T14:35:35.233+0000] {processor.py:186} INFO - Started process (PID=36300) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:35:35.234+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:35:35.237+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:35:35.237+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:35:35.255+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:35:35.252+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:35:35.256+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:35:35.279+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.052 seconds
[2024-11-30T14:36:06.318+0000] {processor.py:186} INFO - Started process (PID=36366) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:36:06.319+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:36:06.323+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:36:06.322+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:36:06.339+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:36:06.336+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:36:06.340+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:36:06.357+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.048 seconds
[2024-11-30T14:36:36.972+0000] {processor.py:186} INFO - Started process (PID=36433) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:36:36.973+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:36:36.976+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:36:36.975+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:36:36.992+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:36:36.988+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:36:36.993+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:36:37.012+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.046 seconds
[2024-11-30T14:37:07.817+0000] {processor.py:186} INFO - Started process (PID=36499) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:37:07.819+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:37:07.823+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:37:07.822+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:37:07.842+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:37:07.838+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:37:07.843+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:37:07.861+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.054 seconds
[2024-11-30T14:37:37.923+0000] {processor.py:186} INFO - Started process (PID=36565) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:37:37.924+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:37:37.926+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:37:37.926+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:37:37.944+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:37:37.940+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:37:37.946+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:37:37.970+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.054 seconds
[2024-11-30T14:38:08.383+0000] {processor.py:186} INFO - Started process (PID=36631) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:38:08.384+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:38:08.386+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:38:08.386+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:38:08.399+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:38:08.396+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:38:08.400+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:38:08.419+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.041 seconds
[2024-11-30T14:38:38.568+0000] {processor.py:186} INFO - Started process (PID=36697) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:38:38.570+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:38:38.573+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:38:38.573+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:38:38.590+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:38:38.587+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:38:38.591+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:38:38.608+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.050 seconds
[2024-11-30T14:39:09.267+0000] {processor.py:186} INFO - Started process (PID=36763) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:39:09.268+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:39:09.270+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:39:09.269+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:39:09.285+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:39:09.282+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:39:09.286+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:39:09.307+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.050 seconds
[2024-11-30T14:39:40.118+0000] {processor.py:186} INFO - Started process (PID=36829) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:39:40.119+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:39:40.124+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:39:40.124+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:39:40.141+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:39:40.138+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:39:40.142+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:39:40.160+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.050 seconds
[2024-11-30T14:40:10.650+0000] {processor.py:186} INFO - Started process (PID=36901) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:40:10.651+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:40:10.656+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:40:10.655+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:40:10.688+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:40:10.679+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:40:10.690+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:40:10.722+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.091 seconds
[2024-11-30T14:40:40.896+0000] {processor.py:186} INFO - Started process (PID=36967) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:40:40.896+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:40:40.899+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:40:40.898+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:40:40.911+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:40:40.908+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:40:40.912+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:40:40.929+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.039 seconds
[2024-11-30T14:41:11.997+0000] {processor.py:186} INFO - Started process (PID=37029) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:41:11.998+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:41:12.001+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:41:12.000+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:41:12.013+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:41:12.010+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:41:12.014+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:41:12.034+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.043 seconds
[2024-11-30T14:41:42.083+0000] {processor.py:186} INFO - Started process (PID=37083) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:41:42.084+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:41:42.087+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:41:42.086+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:41:42.101+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:41:42.098+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:41:42.102+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:41:42.120+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.042 seconds
[2024-11-30T14:42:13.124+0000] {processor.py:186} INFO - Started process (PID=37149) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:42:13.125+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:42:13.128+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:42:13.128+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:42:13.146+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:42:13.142+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:42:13.148+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:42:13.172+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.055 seconds
[2024-11-30T14:42:43.424+0000] {processor.py:186} INFO - Started process (PID=37216) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:42:43.425+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:42:43.427+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:42:43.427+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:42:43.440+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:42:43.437+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:42:43.441+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:42:43.457+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.039 seconds
[2024-11-30T14:43:13.688+0000] {processor.py:186} INFO - Started process (PID=37280) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:43:13.689+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:43:13.691+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:43:13.691+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:43:13.707+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:43:13.704+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:43:13.708+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:43:13.725+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.043 seconds
[2024-11-30T14:43:43.948+0000] {processor.py:186} INFO - Started process (PID=37338) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:43:43.949+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:43:43.951+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:43:43.950+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:43:43.962+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:43:43.960+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:43:43.963+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:43:43.979+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.036 seconds
[2024-11-30T14:44:14.113+0000] {processor.py:186} INFO - Started process (PID=37392) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:44:14.114+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:44:14.116+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:44:14.116+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:44:14.131+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:44:14.128+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:44:14.132+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:44:14.152+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.045 seconds
[2024-11-30T14:44:45.053+0000] {processor.py:186} INFO - Started process (PID=37456) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:44:45.054+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:44:45.056+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:44:45.056+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:44:45.070+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:44:45.068+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:44:45.072+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:44:45.089+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.042 seconds
[2024-11-30T14:45:15.975+0000] {processor.py:186} INFO - Started process (PID=37521) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:45:15.976+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:45:15.978+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:45:15.978+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:45:16.000+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:45:15.996+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:45:16.001+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:45:16.019+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.049 seconds
[2024-11-30T14:45:46.303+0000] {processor.py:186} INFO - Started process (PID=37583) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:45:46.305+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:45:46.309+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:45:46.308+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:45:46.327+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:45:46.324+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:45:46.328+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:45:46.346+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.052 seconds
[2024-11-30T14:46:16.617+0000] {processor.py:186} INFO - Started process (PID=37649) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:46:16.618+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:46:16.621+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:46:16.620+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:46:16.638+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:46:16.635+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:46:16.641+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:46:16.667+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.055 seconds
[2024-11-30T14:46:46.969+0000] {processor.py:186} INFO - Started process (PID=37715) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:46:46.971+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:46:46.976+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:46:46.975+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:46:47.002+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:46:46.999+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:46:47.003+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:46:47.023+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.068 seconds
[2024-11-30T14:47:17.224+0000] {processor.py:186} INFO - Started process (PID=37781) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:47:17.225+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:47:17.228+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:47:17.227+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:47:17.243+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:47:17.241+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:47:17.244+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:47:17.261+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.042 seconds
[2024-11-30T14:47:47.399+0000] {processor.py:186} INFO - Started process (PID=37847) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:47:47.401+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:47:47.404+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:47:47.403+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:47:47.425+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:47:47.421+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:47:47.427+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:47:47.450+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.059 seconds
[2024-11-30T14:48:17.594+0000] {processor.py:186} INFO - Started process (PID=37913) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:48:17.596+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:48:17.599+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:48:17.598+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:48:17.626+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:48:17.622+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:48:17.627+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:48:17.643+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.056 seconds
[2024-11-30T14:48:48.590+0000] {processor.py:186} INFO - Started process (PID=37979) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:48:48.591+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:48:48.594+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:48:48.593+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:48:48.613+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:48:48.610+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:48:48.614+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:48:48.630+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.046 seconds
[2024-11-30T14:49:18.734+0000] {processor.py:186} INFO - Started process (PID=38045) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:49:18.735+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:49:18.737+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:49:18.737+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:49:18.751+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:49:18.748+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:49:18.752+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:49:18.769+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.040 seconds
[2024-11-30T14:49:49.314+0000] {processor.py:186} INFO - Started process (PID=38111) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:49:49.315+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:49:49.321+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:49:49.321+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:49:49.364+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:49:49.357+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:49:49.366+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:49:49.389+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.082 seconds
[2024-11-30T14:50:19.837+0000] {processor.py:186} INFO - Started process (PID=38177) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:50:19.838+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:50:19.841+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:50:19.840+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:50:19.855+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:50:19.853+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:50:19.856+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:50:19.874+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.043 seconds
[2024-11-30T14:50:50.325+0000] {processor.py:186} INFO - Started process (PID=38243) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:50:50.326+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:50:50.329+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:50:50.329+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:50:50.343+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:50:50.340+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:50:50.344+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:50:50.361+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.041 seconds
[2024-11-30T14:51:21.024+0000] {processor.py:186} INFO - Started process (PID=38309) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:51:21.025+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:51:21.029+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:51:21.028+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:51:21.042+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:51:21.039+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:51:21.043+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:51:21.061+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.044 seconds
[2024-11-30T14:51:51.162+0000] {processor.py:186} INFO - Started process (PID=38375) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:51:51.163+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:51:51.166+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:51:51.166+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:51:51.178+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:51:51.175+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:51:51.179+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:51:51.199+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.043 seconds
[2024-11-30T14:52:21.780+0000] {processor.py:186} INFO - Started process (PID=38441) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:52:21.781+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:52:21.784+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:52:21.784+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:52:21.800+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:52:21.796+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:52:21.801+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:52:21.818+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.044 seconds
[2024-11-30T14:52:52.366+0000] {processor.py:186} INFO - Started process (PID=38507) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:52:52.367+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:52:52.370+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:52:52.370+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:52:52.383+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:52:52.381+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:52:52.385+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:52:52.401+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.041 seconds
[2024-11-30T14:53:22.658+0000] {processor.py:186} INFO - Started process (PID=38573) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:53:22.659+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:53:22.662+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:53:22.662+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:53:22.679+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:53:22.677+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:53:22.681+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:53:22.699+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.046 seconds
[2024-11-30T14:53:53.010+0000] {processor.py:186} INFO - Started process (PID=38639) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:53:53.011+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:53:53.014+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:53:53.014+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:53:53.031+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:53:53.028+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:53:53.032+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:53:53.048+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.043 seconds
[2024-11-30T14:54:23.166+0000] {processor.py:186} INFO - Started process (PID=38705) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:54:23.167+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:54:23.169+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:54:23.169+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:54:23.188+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:54:23.185+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:54:23.189+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:54:23.206+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.045 seconds
[2024-11-30T14:54:53.498+0000] {processor.py:186} INFO - Started process (PID=38771) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:54:53.499+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:54:53.502+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:54:53.502+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:54:53.517+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:54:53.514+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:54:53.518+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:54:53.536+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.044 seconds
[2024-11-30T14:55:24.475+0000] {processor.py:186} INFO - Started process (PID=38837) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:55:24.476+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:55:24.478+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:55:24.477+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:55:24.490+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:55:24.488+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:55:24.491+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:55:24.506+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.037 seconds
[2024-11-30T14:55:55.114+0000] {processor.py:186} INFO - Started process (PID=38903) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:55:55.115+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:55:55.117+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:55:55.117+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:55:55.131+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:55:55.128+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:55:55.132+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:55:55.149+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.040 seconds
[2024-11-30T14:56:25.987+0000] {processor.py:186} INFO - Started process (PID=38969) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:56:25.988+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:56:25.991+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:56:25.990+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:56:26.004+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:56:26.001+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:56:26.006+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:56:26.025+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.045 seconds
[2024-11-30T14:56:56.648+0000] {processor.py:186} INFO - Started process (PID=39035) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:56:56.649+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:56:56.651+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:56:56.651+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:56:56.666+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:56:56.663+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:56:56.667+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:56:56.682+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.040 seconds
[2024-11-30T14:57:27.430+0000] {processor.py:186} INFO - Started process (PID=39101) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:57:27.431+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:57:27.434+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:57:27.434+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:57:27.453+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:57:27.449+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:57:27.454+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:57:27.478+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.056 seconds
[2024-11-30T14:57:58.314+0000] {processor.py:186} INFO - Started process (PID=39167) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:57:58.315+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:57:58.318+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:57:58.317+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:57:58.332+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:57:58.329+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:57:58.333+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:57:58.349+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.041 seconds
[2024-11-30T14:58:28.925+0000] {processor.py:186} INFO - Started process (PID=39233) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:58:28.926+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:58:28.928+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:58:28.928+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:58:28.946+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:58:28.942+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:58:28.947+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:58:28.966+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.047 seconds
[2024-11-30T14:58:59.828+0000] {processor.py:186} INFO - Started process (PID=39299) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:58:59.829+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:58:59.833+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:58:59.832+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:58:59.851+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:58:59.846+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:58:59.852+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:58:59.875+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.053 seconds
[2024-11-30T14:59:30.530+0000] {processor.py:186} INFO - Started process (PID=39365) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:59:30.531+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T14:59:30.535+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:59:30.534+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:59:30.555+0000] {logging_mixin.py:190} INFO - [2024-11-30T14:59:30.551+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T14:59:30.556+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T14:59:30.574+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.051 seconds
[2024-11-30T15:00:01.188+0000] {processor.py:186} INFO - Started process (PID=39431) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:00:01.189+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T15:00:01.193+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:00:01.192+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:00:01.212+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:00:01.210+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T15:00:01.213+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:00:01.230+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.049 seconds
[2024-11-30T15:00:31.440+0000] {processor.py:186} INFO - Started process (PID=39498) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:00:31.441+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T15:00:31.444+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:00:31.443+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:00:31.459+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:00:31.456+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T15:00:31.460+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:00:31.477+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.042 seconds
[2024-11-30T15:01:02.187+0000] {processor.py:186} INFO - Started process (PID=39564) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:01:02.188+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T15:01:02.191+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:01:02.190+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:01:02.207+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:01:02.204+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T15:01:02.208+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:01:02.224+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.042 seconds
[2024-11-30T15:01:32.567+0000] {processor.py:186} INFO - Started process (PID=39630) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:01:32.568+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T15:01:32.570+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:01:32.570+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:01:32.586+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:01:32.583+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T15:01:32.587+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:01:32.607+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.045 seconds
[2024-11-30T15:02:02.898+0000] {processor.py:186} INFO - Started process (PID=39696) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:02:02.898+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T15:02:02.901+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:02:02.901+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:02:02.920+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:02:02.916+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T15:02:02.922+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:02:02.944+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.053 seconds
[2024-11-30T15:02:33.181+0000] {processor.py:186} INFO - Started process (PID=39762) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:02:33.182+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T15:02:33.184+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:02:33.184+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:02:33.197+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:02:33.194+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T15:02:33.198+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:02:33.214+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.039 seconds
[2024-11-30T15:03:03.624+0000] {processor.py:186} INFO - Started process (PID=39828) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:03:03.625+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T15:03:03.628+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:03:03.628+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:03:03.642+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:03:03.640+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T15:03:03.643+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:03:03.661+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.043 seconds
[2024-11-30T15:03:34.027+0000] {processor.py:186} INFO - Started process (PID=39894) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:03:34.028+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T15:03:34.030+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:03:34.030+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:03:34.044+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:03:34.041+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T15:03:34.045+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:03:34.062+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.041 seconds
[2024-11-30T15:04:04.262+0000] {processor.py:186} INFO - Started process (PID=39960) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:04:04.263+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T15:04:04.266+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:04:04.265+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:04:04.283+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:04:04.278+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T15:04:04.284+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:04:04.303+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.048 seconds
[2024-11-30T15:04:34.425+0000] {processor.py:186} INFO - Started process (PID=40026) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:04:34.426+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T15:04:34.428+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:04:34.428+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:04:34.442+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:04:34.440+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T15:04:34.443+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:04:34.461+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.041 seconds
[2024-11-30T15:05:04.542+0000] {processor.py:186} INFO - Started process (PID=40092) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:05:04.542+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T15:05:04.545+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:05:04.544+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:05:04.559+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:05:04.556+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T15:05:04.559+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:05:04.577+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.040 seconds
[2024-11-30T15:05:35.045+0000] {processor.py:186} INFO - Started process (PID=40159) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:05:35.047+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T15:05:35.049+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:05:35.049+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:05:35.065+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:05:35.062+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T15:05:35.066+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:05:35.083+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.043 seconds
[2024-11-30T15:06:05.292+0000] {processor.py:186} INFO - Started process (PID=40225) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:06:05.293+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T15:06:05.297+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:06:05.296+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:06:05.315+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:06:05.312+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T15:06:05.316+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:06:05.335+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.052 seconds
[2024-11-30T15:06:35.778+0000] {processor.py:186} INFO - Started process (PID=40291) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:06:35.779+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T15:06:35.783+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:06:35.782+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:06:35.799+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:06:35.796+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T15:06:35.800+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:06:35.817+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.047 seconds
[2024-11-30T15:07:06.069+0000] {processor.py:186} INFO - Started process (PID=40357) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:07:06.070+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T15:07:06.073+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:07:06.072+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:07:06.094+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:07:06.089+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T15:07:06.101+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:07:06.132+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.071 seconds
[2024-11-30T15:07:36.705+0000] {processor.py:186} INFO - Started process (PID=40423) to work on /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:07:36.706+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/firebase_to_s3_to_rds.py for tasks to queue
[2024-11-30T15:07:36.708+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:07:36.708+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:07:36.724+0000] {logging_mixin.py:190} INFO - [2024-11-30T15:07:36.720+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/firebase_to_s3_to_rds.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 7, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2024-11-30T15:07:36.725+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/firebase_to_s3_to_rds.py
[2024-11-30T15:07:36.749+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/firebase_to_s3_to_rds.py took 0.050 seconds
