[2024-12-06T00:49:58.167+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-06T00:49:58.184+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: firestore_to_s3_to_rd.transform_and_upload_to_s3 manual__2024-12-06T00:49:53.165788+00:00 [queued]>
[2024-12-06T00:49:58.191+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: firestore_to_s3_to_rd.transform_and_upload_to_s3 manual__2024-12-06T00:49:53.165788+00:00 [queued]>
[2024-12-06T00:49:58.191+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-06T00:49:58.206+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform_and_upload_to_s3> on 2024-12-06 00:49:53.165788+00:00
[2024-12-06T00:49:58.212+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2809) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-06T00:49:58.214+0000] {standard_task_runner.py:72} INFO - Started process 2811 to run task
[2024-12-06T00:49:58.214+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'firestore_to_s3_to_rd', 'transform_and_upload_to_s3', 'manual__2024-12-06T00:49:53.165788+00:00', '--job-id', '214', '--raw', '--subdir', 'DAGS_FOLDER/firebase_to_s3_to_rds.py', '--cfg-path', '/tmp/tmpx8o9rcpa']
[2024-12-06T00:49:58.215+0000] {standard_task_runner.py:105} INFO - Job 214: Subtask transform_and_upload_to_s3
[2024-12-06T00:49:58.257+0000] {task_command.py:467} INFO - Running <TaskInstance: firestore_to_s3_to_rd.transform_and_upload_to_s3 manual__2024-12-06T00:49:53.165788+00:00 [running]> on host 4b3a7f9b2751
[2024-12-06T00:49:58.337+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='firestore_to_s3_to_rd' AIRFLOW_CTX_TASK_ID='transform_and_upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-12-06T00:49:53.165788+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-06T00:49:53.165788+00:00'
[2024-12-06T00:49:58.339+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-06T00:49:58.339+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-06T00:49:58.339+0000] {logging_mixin.py:190} INFO - Current task name:transform_and_upload_to_s3 state:running start_date:2024-12-06 00:49:58.185225+00:00
[2024-12-06T00:49:58.340+0000] {logging_mixin.py:190} INFO - Dag name:firestore_to_s3_to_rd and current dag run status:running
[2024-12-06T00:49:58.340+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-06T00:49:58.349+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 67, in transform_and_upload_to_s3
    writer.writerow([item[key]['stringValue'] for key in header])
                     ~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'stringValue'
[2024-12-06T00:49:58.359+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-06T00:49:58.360+0000] {logging_mixin.py:190} INFO - Task start:2024-12-06 00:49:58.185225+00:00 end:2024-12-06 00:49:58.359037+00:00 duration:0.173812
[2024-12-06T00:49:58.361+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transform_and_upload_to_s3> dag:<DAG: firestore_to_s3_to_rd> dagrun:<DagRun firestore_to_s3_to_rd @ 2024-12-06 00:49:53.165788+00:00: manual__2024-12-06T00:49:53.165788+00:00, state:running, queued_at: 2024-12-06 00:49:53.175532+00:00. externally triggered: True>
[2024-12-06T00:49:58.361+0000] {logging_mixin.py:190} INFO - Failure caused by 'stringValue'
[2024-12-06T00:49:58.362+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=firestore_to_s3_to_rd, task_id=transform_and_upload_to_s3, run_id=manual__2024-12-06T00:49:53.165788+00:00, execution_date=20241206T004953, start_date=20241206T004958, end_date=20241206T004958
[2024-12-06T00:49:58.555+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-06T00:49:58.555+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 214 for task transform_and_upload_to_s3 ('stringValue'; 2811)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 67, in transform_and_upload_to_s3
    writer.writerow([item[key]['stringValue'] for key in header])
                     ~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'stringValue'
[2024-12-06T00:49:58.589+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-06T00:49:58.610+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-06T00:49:58.615+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
